Compiler error fix.
How can this every have compiled? Please don't push commits
without first at least compiling it :/

Using '#else if' instead of '#elif'?!

indra/newview/llappviewer.cpp:797:7: error: extra tokens at end of #else directive